# Generated by Django 5.2 on 2025-05-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_conversation_job_alter_conversation_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='job',
        ),
    ]
