# Generated by Django 5.2 on 2025-05-01 10:45

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_remove_conversation_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='document',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='content/static/conversation_documents/'), upload_to='conversation_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), django.core.validators.MaxValueValidator(10485760, message='Document size cannot exceed 10 MB.')]),
        ),
    ]
