# Generated by Django 5.2 on 2025-05-01 10:49

import conversation.models
import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_conversationmessage_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='document',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='content/static/conversation_documents/'), upload_to='conversation_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), conversation.models.validate_document_size]),
        ),
    ]
