# Generated by Django 5.2 on 2025-05-02 10:15

import conversation.models
import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0005_alter_conversationmessage_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='document',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/conversation_documents/', location='content/media/conversation_documents/'), upload_to='conversation_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), conversation.models.validate_document_size]),
        ),
    ]
