# Generated by Django 5.0.3 on 2025-04-10 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('freelancer', '0002_freelancercertification_freelancereducation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerskill',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='freelancerskill',
            unique_together={('freelancer', 'skill')},
        ),
        migrations.RemoveField(
            model_name='freelancerskill',
            name='name',
        ),
    ]
