# Generated by Django 5.0.3 on 2025-04-10 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_alter_freelancerskill_unique_together_and_more'),
        ('job', '0003_review_fast_turnaround_review_knowledge_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.skill'),
        ),
    ]
