# Generated by Django 5.0.3 on 2025-04-15 04:11

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0005_alter_freelancer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='freelancer_images', validators=[core.validators.validate_image_size, core.validators.validate_image_type, core.validators.validate_image_dimensions]),
        ),
        migrations.AlterField(
            model_name='freelancerproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images', validators=[core.validators.validate_image_size, core.validators.validate_image_type, core.validators.validate_image_dimensions]),
        ),
    ]
