# Generated by Django 5.2 on 2025-05-02 10:21

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0013_add_updated_at_and_fix_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='cv',
            field=models.URLField(blank=True, null=True, validators=[core.validators.validate_url]),
        ),
    ]
