# Generated by Django 5.2 on 2025-05-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0014_freelancer_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
