# Generated by Django 5.2 on 2025-05-29 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0015_freelancer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='bkash_account',
            field=models.CharField(blank=True, help_text='Your bKash account number (Personal Only) - Not shown publicly', max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='invalid_bkash', message='bKash account number must be 11 digits and start with 01', regex='^01[0-9]{9}$')]),
        ),
    ]
