# Generated by Django 5.2 on 2025-05-29 18:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0016_freelancer_bkash_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('free', 'Free Plan'), ('member', 'Member Plan'), ('pro', 'Pro Plan')], default='free', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='active', max_length=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Transaction ID must be exactly 10 digits')])),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
