# Generated by Django 5.2 on 2025-05-30 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0018_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='verified_by',
        ),
    ]
