# Generated by Django 5.2 on 2025-05-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0019_remove_subscription_verified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='github',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='video_introduction',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='website',
        ),
    ]
