# Generated by Django 5.2 on 2025-06-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0020_remove_social_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
