# Generated by Django 5.2 on 2025-06-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0021_delete_company'),
    ]

    operations = [
    ]
