# Generated by Django 5.2 on 2025-06-15 06:52

from django.db import migrations, models
import django.db.models.deletion

def set_default_plan(apps, schema_editor):
    Subscription = apps.get_model('freelancer', 'Subscription')
    SubscriptionPlan = apps.get_model('freelancer', 'SubscriptionPlan')
    # Get or create the free plan
    free_plan, _ = SubscriptionPlan.objects.get_or_create(
        name='free',
        defaults={
            'proposal_limit': 5,
            'job_post_limit': 5,
            'price': 0,
            'duration_days': 30
        }
    )
    # Update all subscriptions with null plan to use free plan
    Subscription.objects.filter(plan__isnull=True).update(plan=free_plan)

class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0023_auto_20250615_1250'),
    ]

    operations = [
        migrations.RunPython(set_default_plan),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='freelancer.subscriptionplan'),
        ),
    ]
