# Generated by Django 5.2 on 2025-06-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0025_rename_start_date_subscription_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='freelancer_cvs'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='bkash_account',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancers', to='freelancer.category'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='hourly_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
