# Generated by Django 5.2 on 2025-06-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0027_fix_null_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='fullname',
            field=models.CharField(max_length=30),
        ),
    ]
