# Generated by Django 5.2 on 2025-06-21 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0028_alter_freelancer_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='hourly_rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
