# Generated by Django 5.2.4 on 2025-07-14 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0029_alter_freelancer_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='hourly_rate',
            field=models.IntegerField(default=150, validators=[django.core.validators.MinValueValidator(150), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
