# Generated by Django 4.2.3 on 2025-04-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', to='job.skill'),
        ),
    ]
