# Generated by Django 5.0.3 on 2025-04-15 04:11

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images', validators=[core.validators.validate_image_size, core.validators.validate_image_type, core.validators.validate_image_dimensions]),
        ),
    ]
