# Generated by Django 5.2 on 2025-06-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_job_payment_verified_job_refund_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='document_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
