# Generated by Django 5.2 on 2025-06-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_job_document_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='document_token',
        ),
    ]
