# Generated by Django 5.2 on 2025-06-21 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_remove_contract_client_alter_contract_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='proposed_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
