# Generated by Django 5.2 on 2025-07-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.PositiveIntegerField(blank=True, help_text='Deadline in days', null=True),
        ),
    ]
